---
- lineage:
  - startswith:
    - ipv4 access-list
    - no ipv4 access-list
  add_tags: push
- lineage:
  - startswith: router bgp
  - startswith: address-family
  - startswith:
    - neighbor
    - no neighbor
    - maximum-paths
    - exit-address-family
  add_tags: push
- lineage:
  - startswith: router bgp
  - startswith:
    - neighbor
    - no neighbor
  add_tags: push
- lineage:
  - startswith: ''
    negative_intersection_tags: ['push']
  match_leaf: true
  add_tags: ignore
